# Site settings
title: "LIPS: Powerful Scheme based lisp interpreter in JavaScript"
email: "jcubic@jcubic.pl"
twitter: "jcubic"
description: "Modern and powerful lisp language written in JavaScript with literal regexes, that auto resolve promises, full access to JavaScript, lisp macro system and hygienic macros."
baseurl: ""

permalink: "/blog/:title.html"

plugins: [jekyll-paginate]
paginate: 10
paginate_path: "/blog/page:num"

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
